image: python:3.7

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - pip install --upgrade pip virtualenv virtualenvwrapper
  - pip install poetry

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip virtualenv virtualenvwrapper wheel
    - poetry install --no-dev

    # optional dependency for metrics
    - git clone git@gitlab.com:OverTrack/overtrack_2_api.git
    - mv -t overtrack_web ./overtrack_2_api/api
    - git clone git@gitlab.com:OverTrack/overtrack-v2.git
    - mv -t overtrack_web ./overtrack-v2/overtrack
    - git clone git@gitlab.com:OverTrack/overtrack-models.git
    - mv -t overtrack_web ./overtrack-models/overtrack_models  # ??? why does poetry no longer install this from deps?

    - pushd overtrack_web

    # - zappa update test || { sleep 30; zappa tail test --since 1min --disable-keep-open; false; }
    - zappa update main

    # install with dev deps this time
    - poetry install
    - boussole compile

    - pip install awscli
    - aws s3 sync ./static/ s3://overtrack-web-2-assets/static --delete --acl public-read --cache-control max-age=86400
    - aws s3 cp s3://overtrack-web-2-assets/static/images s3://overtrack-web-2-assets/static/images --recursive --acl public-read --cache-control max-age=604800 --metadata-directive REPLACE
    - aws s3 cp s3://overtrack-web-2-assets/static/js/lib s3://overtrack-web-2-assets/static/js/lib --recursive --acl public-read --cache-control max-age=6048000 --metadata-directive REPLACE
    - aws configure set preview.cloudfront true
    - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/static/*"

  only:
    - master
    - "apex.overtrack.gg"
